"""Constantes y configuración por entorno para ejecutar KORLIC v2."""

from __future__ import annotations

import os

DEFAULT_GAMMA_BASE_URL = "https://gamma-api.polymarket.com"
DEFAULT_CLOB_HOST = "https://clob.polymarket.com"
DEFAULT_GAMMA_MIN_INTERVAL_SECONDS = 0.25
DEFAULT_CLOB_MIN_INTERVAL_SECONDS = 0.05
DEFAULT_GAMMA_PAGE_LIMIT = 100
DEFAULT_GAMMA_MAX_PAGES = 0
DEFAULT_GAMMA_SEED_EVENT_SLUG = "btc-updown-5m-1774854300"
DEFAULT_GAMMA_FAMILY_PREFIX = "btc-updown-5m-"

DEFAULT_SIGNAL_ENTRY_PRICE = 0.60
DEFAULT_SIGNAL_ENTRY_SECONDS = 600
DEFAULT_SIGNAL_MIN_DEPTH = 10.0
DEFAULT_SIGNAL_MIN_SIZE = 5.0
DEFAULT_SIGNAL_MAX_STAKE = 25.0
DEFAULT_MARKET_SIDE_MODE = "BOTH"
DEFAULT_MARKET_MIN_VOLUME_M = 0.0
DEFAULT_MARKET_MIN_LIQUIDITY_M = 1000.0
DEFAULT_MARKET_MAX_SPREAD = 1.0

# Configuración final: defaults + override por variables de entorno.
KORLIC_GAMMA_BASE_URL = os.getenv("KORLIC_GAMMA_BASE_URL", DEFAULT_GAMMA_BASE_URL)
KORLIC_CLOB_HOST = os.getenv("KORLIC_CLOB_HOST", DEFAULT_CLOB_HOST)
KORLIC_GAMMA_MIN_INTERVAL_SECONDS = float(
    os.getenv("KORLIC_GAMMA_MIN_INTERVAL_SECONDS", str(DEFAULT_GAMMA_MIN_INTERVAL_SECONDS))
)
KORLIC_CLOB_MIN_INTERVAL_SECONDS = float(
    os.getenv("KORLIC_CLOB_MIN_INTERVAL_SECONDS", str(DEFAULT_CLOB_MIN_INTERVAL_SECONDS))
)
KORLIC_GAMMA_PAGE_LIMIT = int(os.getenv("KORLIC_GAMMA_PAGE_LIMIT", str(DEFAULT_GAMMA_PAGE_LIMIT)))
KORLIC_GAMMA_MAX_PAGES = int(os.getenv("KORLIC_GAMMA_MAX_PAGES", str(DEFAULT_GAMMA_MAX_PAGES)))
KORLIC_GAMMA_SEED_EVENT_SLUG = os.getenv("KORLIC_GAMMA_SEED_EVENT_SLUG", DEFAULT_GAMMA_SEED_EVENT_SLUG)
KORLIC_GAMMA_FAMILY_PREFIX = os.getenv("KORLIC_GAMMA_FAMILY_PREFIX", DEFAULT_GAMMA_FAMILY_PREFIX)
KORLIC_SIGNAL_ENTRY_PRICE = float(os.getenv("KORLIC_SIGNAL_ENTRY_PRICE", str(DEFAULT_SIGNAL_ENTRY_PRICE)))
KORLIC_SIGNAL_ENTRY_SECONDS = int(os.getenv("KORLIC_SIGNAL_ENTRY_SECONDS", str(DEFAULT_SIGNAL_ENTRY_SECONDS)))
KORLIC_SIGNAL_MIN_DEPTH = float(os.getenv("KORLIC_SIGNAL_MIN_DEPTH", str(DEFAULT_SIGNAL_MIN_DEPTH)))
KORLIC_SIGNAL_MIN_SIZE = float(os.getenv("KORLIC_SIGNAL_MIN_SIZE", str(DEFAULT_SIGNAL_MIN_SIZE)))
KORLIC_SIGNAL_MAX_STAKE = float(os.getenv("KORLIC_SIGNAL_MAX_STAKE", str(DEFAULT_SIGNAL_MAX_STAKE)))
KORLIC_MARKET_SIDE_MODE = os.getenv("KORLIC_MARKET_SIDE_MODE", DEFAULT_MARKET_SIDE_MODE).strip().upper()
KORLIC_MARKET_MIN_VOLUME_M = float(os.getenv("KORLIC_MARKET_MIN_VOLUME_M", str(DEFAULT_MARKET_MIN_VOLUME_M)))
KORLIC_MARKET_MIN_LIQUIDITY_M = float(os.getenv("KORLIC_MARKET_MIN_LIQUIDITY_M", str(DEFAULT_MARKET_MIN_LIQUIDITY_M)))
KORLIC_MARKET_MAX_SPREAD = float(os.getenv("KORLIC_MARKET_MAX_SPREAD", str(DEFAULT_MARKET_MAX_SPREAD)))
